#!/usr/bin/env bash

# Verify some settings with the user...

SERVICE=camera-record.service
SYSTEMD_EXEC_PATH=$(grep ExecStart= $SERVICE | cut -d = -f 2)
MY_PATH=$(pwd)
USER=$(grep User= $SERVICE | cut -d = -f 2)
GROUP=$(grep Group= $SERVICE | cut -d = -f 2)

INSTALL_SERVICE="sudo cp $SERVICE /etc/systemd/system"
ENABLE_SERVICE="sudo systemctl enable $SERVICE"
DAEMON_RELOAD="sudo systemctl daemon-reload"

echo
echo "This script should be run from the root of the raspi-video-recorder"
echo "repository.  It looks like it is being run from:"
echo "  $MY_PATH/record"
echo
echo "Systemd will think that it is installed to:"
echo "  $SYSTEMD_EXEC_PATH"
echo
echo "The above two paths should match.  Otherwise, edit"
echo "$SERVICE and change the ExecStart line."
echo
echo "This script will run as user $USER and group $GROUP."
echo
echo "If this does not please, then edit $SERVICE and change"
echo "the User and Group lines."
echo
echo "If you say 'yes' below, this script will execute:"
echo "  $INSTALL_SERVICE"
echo "  $ENABLE_SERVICE"
echo "  $DAEMON_RELOAD"
echo "You may be prompted for a password by sudo.  The default"
echo "password is 'raspberry'."
echo

while read -p "Install? (yes/no) " DOINSTALL; do
  if [ x$DOINSTALL == "xno" ]; then
    echo "Not Installing."
    exit
  elif [ x$DOINSTALL == "xyes" ]; then
    break
  else
    echo "Please enter 'yes' or 'no'."
  fi
done

echo

$INSTALL_SERVICE
$ENABLE_SERVICE
$DAEMON_RELOAD

echo
echo "You may now wish to run 'sudo systemctl start $SERVICE',"
echo "which will start recording to $MY_PATH/vids.  It is configured to"
echo "automatically start on next boot."
echo
